export const ECUADOR_PICKUPS = [
  { slug: "chevrolet-dmax", brand: "Chevrolet", model: "D-Max", aliases: ["Dmax", "D MAX"], focus: "work", profile: "Una pickup de trabajo muy extendida en Ecuador que también admite proyectos de aventura, protección y carga." },
  { slug: "chevrolet-colorado", brand: "Chevrolet", model: "Colorado", aliases: [], focus: "adventure", profile: "Una camioneta mediana para combinar uso diario, remolque y preparación off-road con componentes seleccionados." },
  { slug: "chevrolet-silverado", brand: "Chevrolet", model: "Silverado", aliases: [], focus: "fullsize", profile: "Una pickup full-size que requiere accesorios acordes con sus dimensiones, peso y capacidad de trabajo." },
  { slug: "toyota-hilux", brand: "Toyota", model: "Hilux", aliases: [], focus: "work", profile: "Una referencia de trabajo y 4x4 en Ecuador, compatible con proyectos de protección, carga y suspensión según versión." },
  { slug: "toyota-tacoma", brand: "Toyota", model: "Tacoma", aliases: [], focus: "adventure", profile: "Una pickup orientada a aventura que se beneficia de equipamiento modular, rescate y protección para rutas exigentes." },
  { slug: "toyota-tundra", brand: "Toyota", model: "Tundra", aliases: [], focus: "fullsize", profile: "Una camioneta de gran formato para proyectos premium de carga, remolque y presencia off-road." },
  { slug: "ford-ranger", brand: "Ford", model: "Ranger", aliases: ["Ranger Raptor"], focus: "adventure", profile: "Una pickup versátil para trabajo y aventura, con múltiples generaciones que exigen validar cada aplicación." },
  { slug: "ford-f150", brand: "Ford", model: "F-150", aliases: ["F150", "F 150", "Raptor"], focus: "fullsize", profile: "Una pickup full-size con configuraciones de balde y chasis que requieren equipamiento dedicado." },
  { slug: "ford-maverick", brand: "Ford", model: "Maverick", aliases: [], focus: "compact", profile: "Una pickup compacta para uso urbano y escapadas que prioriza soluciones ligeras, prácticas y bien integradas." },
  { slug: "nissan-frontier", brand: "Nissan", model: "Frontier", aliases: ["Navara", "NP300"], focus: "work", profile: "Una camioneta de trabajo y todo terreno con distintas generaciones conocidas como Frontier, Navara o NP300." },
  { slug: "mitsubishi-l200-triton", brand: "Mitsubishi", model: "L200 / Triton", aliases: ["L200", "Triton"], focus: "work", profile: "Una pickup de uso productivo y 4x4 que necesita compatibilidad por generación, cabina y configuración del balde." },
  { slug: "mazda-bt50", brand: "Mazda", model: "BT-50", aliases: ["BT50", "BT 50"], focus: "work", profile: "Una camioneta con amplio parque circulante en Ecuador para proyectos de carga, protección y remolque." },
  { slug: "gwm-poer", brand: "GWM", model: "Poer", aliases: ["Great Wall Poer", "Poer 500"], focus: "premium", profile: "Una pickup moderna que combina confort y capacidad, ideal para accesorios funcionales con acabado premium." },
  { slug: "gwm-wingle", brand: "GWM", model: "Wingle", aliases: ["Wingle 5", "Wingle 7", "Wingle S"], focus: "work", profile: "Una familia de camionetas ensambladas y comercializadas en Ecuador con varias cabinas, años y medidas de balde." },
  { slug: "jac-t6", brand: "JAC", model: "T6", aliases: [], focus: "work", profile: "Una pickup productiva que admite soluciones de protección, remolque y organización de carga." },
  { slug: "jac-t8", brand: "JAC", model: "T8", aliases: ["T8 Pro"], focus: "mixed", profile: "Una camioneta de trabajo y uso personal que puede equiparse para carga diaria o aventura de fin de semana." },
  { slug: "jac-t9", brand: "JAC", model: "T9", aliases: [], focus: "premium", profile: "Una pickup de nueva generación para proyectos que buscan protección, tecnología y una presencia 4x4 más marcada." },
  { slug: "jmc-vigus", brand: "JMC", model: "Vigus", aliases: ["Vigus Plus", "Vigus 7"], focus: "work", profile: "Una camioneta enfocada en trabajo que requiere accesorios resistentes y aplicaciones confirmadas por versión." },
  { slug: "foton-tunland", brand: "Foton", model: "Tunland", aliases: ["Tunland G7", "Tunland G9", "Tunland V9"], focus: "work", profile: "Una familia de pickups de trabajo con diferentes generaciones, dimensiones y necesidades de carga." },
  { slug: "dongfeng-rich6", brand: "Dongfeng", model: "Rich 6", aliases: ["Rich6"], focus: "work", profile: "Una pickup para operación diaria que puede mejorar protección del balde, remolque y funcionalidad." },
  { slug: "dongfeng-rich7", brand: "Dongfeng", model: "Rich 7", aliases: ["Rich7"], focus: "mixed", profile: "Una camioneta que combina trabajo y equipamiento personal, con opciones para carga y aventura." },
  { slug: "dongfeng-z9", brand: "Dongfeng", model: "Z9", aliases: [], focus: "premium", profile: "Una pickup moderna que exige accesorios bien integrados y verificación técnica antes de instalar." },
  { slug: "kia-tasman", brand: "Kia", model: "Tasman", aliases: [], focus: "adventure", profile: "Una pickup de nueva generación pensada para trabajo y aventura, con aplicaciones que deben validarse por versión." },
  { slug: "volkswagen-amarok", brand: "Volkswagen", model: "Amarok", aliases: [], focus: "premium", profile: "Una camioneta de enfoque premium que combina carretera, trabajo y capacidad 4x4." },
  { slug: "ram-700", brand: "RAM", model: "700", aliases: [], focus: "compact", profile: "Una pickup compacta para carga urbana que necesita accesorios ligeros y compatibles con su balde." },
  { slug: "ram-1000", brand: "RAM", model: "1000", aliases: [], focus: "compact", profile: "Una camioneta compacta orientada a versatilidad diaria, protección de carga y transporte recreativo." },
  { slug: "ram-1500", brand: "RAM", model: "1500", aliases: ["RAM 1500", "TRX"], focus: "fullsize", profile: "Una pickup full-size para equipamiento premium, remolque y proyectos off-road de mayor escala." },
  { slug: "changan-hunter", brand: "Changan", model: "Hunter", aliases: [], focus: "mixed", profile: "Una camioneta multipropósito para trabajo, viaje y equipamiento de carga según su configuración." },
  { slug: "maxus-t60", brand: "Maxus", model: "T60", aliases: [], focus: "work", profile: "Una pickup de trabajo con opciones para proteger el balde y mejorar remolque, carga y acceso." },
  { slug: "maxus-t90", brand: "Maxus", model: "T90", aliases: [], focus: "premium", profile: "Una camioneta de mayor equipamiento que se presta para soluciones premium de carga y protección." },
  { slug: "peugeot-landtrek", brand: "Peugeot", model: "Landtrek", aliases: [], focus: "mixed", profile: "Una pickup mediana para trabajo y uso personal con aplicaciones variables según año y versión." },
  { slug: "renault-oroch", brand: "Renault", model: "Oroch", aliases: ["Duster Oroch"], focus: "compact", profile: "Una pickup compacta para ciudad y escapadas que prioriza carga práctica y accesorios de bajo peso." },
  { slug: "fiat-titano", brand: "Fiat", model: "Titano", aliases: [], focus: "mixed", profile: "Una camioneta mediana para uso productivo y personal que requiere validar accesorios por versión." },
  { slug: "isuzu-dmax", brand: "Isuzu", model: "D-Max", aliases: ["Isuzu Dmax"], focus: "work", profile: "Una pickup de trabajo reconocida por durabilidad, con aplicaciones que cambian según origen, año y cabina." },
  { slug: "shineray-t30-t32", brand: "Shineray", model: "T30 / T32", aliases: ["T30", "T32"], focus: "compact", profile: "Pickups compactas de operación urbana para soluciones sencillas de carga y protección." }
];

export const pickupName = (pickup) => `${pickup.brand} ${pickup.model}`;
